config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations'
  }


  root "storefront#index"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :users, except: [:new, :create]

  resources :products
  
  resources :sales 
  
  resources :users do
    member do
      patch :activate
      patch :deactivate
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :sales
    
    enum :role, { 
      Empleado: 0, 
      Gerente: 1, 
      Administrador: 2 
    }
  
    # Validations
    validates :username,  
        presence: { message: "El nombre de usuario no puede estar en blanco" },
        uniqueness: { message: "Este nombre de usuario ya se encuentra en uso" }

    validates :email, 
        presence: { message: "El correo electrónico no puede estar en blanco" },
        uniqueness: { message: "Este correo electrónico ya está registrado" },
                    format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :phone, presence: true
    
    # Asegurar que esté en true por defecto al crear
    before_validation :set_default_active, on: :create

    def deactivate
      # Guardar el digest de la contraseña original
      self.update(active: false, original_password: self.password)
  
      # Cambiar la contraseña a un valor aleatorio
      new_password = SecureRandom.hex(10)
      self.update(password: new_password)  # Esto actualizará el password_digest
    end
  
    # Método para activar el usuario
    def activate
      # Restaurar el digest de la contraseña original
      self.update(active: true, password: self.original_password)
    end

    private

    def set_default_active
      self.active = true
    end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_action :authenticate_user!, only: [:index, :show]  # Asegura que el usuario esté autenticado
    before_action :authorize_user, only: [:index, :show]  # Verifica si tiene el rol adecuado

    def index
      @users = User.page(params[:page]).per(2)
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
        @roles = current_user.role == "Administrador" ? User.roles.keys : User.roles.keys - ['admin']
    end

    def create
        @user = User.new(user_params)
        @roles = current_user.role == "Administrador" ? User.roles.keys : User.roles.keys - ['admin']
        
        if @user.save
          redirect_to users_path, notice: "Usuario creado correctamente"
        else
          render :new, status: :unprocessable_entity
        end
    end
    
    def edit
        @user = User.find(params[:id]) 
    end

    def update
        @user = User.find(params[:id])
          
        if @user.update(user_params_edit)
          redirect_to users_path, notice: 'Usuario actualizado exitosamente.'
        else
          render :edit
        end
    end
    
    def destroy

      @user = User.find(params[:id])
      if @user.destroy
        redirect_to users_path, notice: 'Usuario eliminado exitosamente'
      else
        redirect_to users_path, alert: 'No se pudo eliminar el usuario'
      end
    end

    def activate
      @user = User.find(params[:id])
      @user.activate
      redirect_to users_path, notice: 'Usuario activado exitosamente.'
    end
  
    def deactivate
      @user = User.find(params[:id])
      @user.deactivate
      redirect_to users_path, notice: 'Usuario desactivado exitosamente.'
    end
    
    private
      def user_params
        params.expect(user: [:username, :email, :phone, :original_password, :entry_date, :role])
      end
      
      def authorize_user
        unless current_user.role == "Administrador" || current_user.role ==  "Gerente"
          render file: "#{Rails.root}/public/403.html", status: :forbidden
        end
      end
end
  

app/views/users/edit.html.erb
<h1 class= "text-center text-lg text-rosa-light font-bold mb-2">Editar Usuario</h1>
<div class="flex justify-center items-center">
  <%= form_with model: @user, html: { style: "width:50%; border: solid 1px black; border-radius:30px; padding:20px;" } do |form| %>
    <div class="mb-2">
      <%= form.label :username, "Nombre de Usuario", class: "block text-sm font-medium text-gray-900 mb-2" %>
      <%= form.text_field :username, placeholder: "Ingrese el nombre de usuario", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-rosa-light focus:border-rosa-light block w-full p-2." %>
    </div>

    <div class="mb-2">
      <%= form.label :email, "Correo electrónico", class: "mb-2 block text-sm font-medium text-gray-900" %>
      <%= form.email_field :email, placeholder: "Ingrese el correo electrónico", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-rosa-light focus:border-rosa-light block w-full p-2" %>
    </div>

    <div class="mb-2">
      <%= form.label :phone, "Número de Teléfono", class: "mb-2 block text-sm font-medium text-gray-900" %>
      <%= form.telephone_field :phone, placeholder: "Ingrese el número de teléfono", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-rosa-light focus:border-rosa-light block w-full p-2" %>
    </div>

    <div class="mb-2">
      <%= form.label :original_password_digest, "Contraseña", class: "mb-2 block text-sm font-medium text-gray-900" %>
      <%= form.password_field :original_password_digest, placeholder: "Ingrese la contraseña", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-rosa-light focus:border-rosa-light block w-full p-2" %>
    </div>

    <div class="mb-2">
      <%= form.label :entry_date, "Fecha de entrada a la cadena", class: "mb-2 block text-sm font-medium text-gray-900" %>
      <%= form.date_field :entry_date, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-rosa-light focus:border-rosa-light block w-full p-2" %>
    </div>

    <div class="mb-2">
      <%= form.label :role, "Selecciona un rol", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
      <%= form.select :role, User.roles.keys.map { |role| [role.humanize, role] }, { prompt: "Selecciona un rol" }, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
    </div>

    <div class="flex justify-center">
      <%= form.submit "Actualizar Usuario", class: "bg-rosa-light text-white rounded-full hover:bg-opacity-90 transition duration-300 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-rosa-light w-1/2 mt-6" %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1 class="font-bold text-rosa-ligth text-3xl text-center mb-2">Listado de Usuarios</h1>

<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
  <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th scope="col" class="px-6 py-3">Usuario</th>
        <th scope="col" class="px-6 py-3">Email</th>
        <th scope="col" class="px-6 py-3">Teléfono</th>
        <th scope="col" class="px-6 py-3">Rol</th>
        <th scope="col" class="px-6 py-3">Activo</th>
        <% if current_user.role != "Empleado" %>
          <th scope="col" class="px-6 py-3">Acción</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
            <span class="text-gray-800"><%= user.username %></span> 
          </th>
          <td class="px-6 py-4">
            <span class="text-gray-800"><%= user.email %></span> 
          </td>
          <td class="px-6 py-4">
            <span class="text-gray-800"><%= user.phone %></span> 
          </td>
          <td class="px-6 py-4">
            <span class="text-gray-800"><%= user.role %></span> 
          </td>
          <td class="px-6 py-4">
            <% if user.active %>
              <span class="text-green-500">Activo</span> 
            <% else %>
              <span class="text-red-500">Desactivado</span>
            <% end %>
          </td>
          <td class="px-6 py-4">
            <% if current_user.role != "Empleado" %>
                <div class="flex">
                  <%= link_to edit_user_registration_path do %>
                    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m14.304 4.844 2.852 2.852M7 7H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-4.5m2.409-9.91a2.017 2.017 0 0 1 0 2.853l-6.844 6.844L8 14l.713-3.565 6.844-6.844a2.015 2.015 0 0 1 2.852 0Z"/>
                    </svg>
                  <% end %>
                  <%= link_to '#', 
                        data: { 
                          bs_toggle: "modal", 
                          bs_target: "#popup-modal", 
                          user_id: user.id 
                        },
                        class: "delete-link" do %>
                        <svg 
                          class="w-6 h-6 text-gray-800 dark:text-white pointer-events-none" 
                          aria-hidden="true" 
                          xmlns="http://www.w3.org/2000/svg" 
                          width="24" 
                          height="24" 
                          fill="none" 
                          viewBox="0 0 24 24"
                        >
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z" />
                        </svg>
                    <% end %>
                      
                      <% if user.role != "Administrador" && current_user.role == "Administrador" %>
                          <% if user.active %>
                            <%= link_to deactivate_user_path(user), data: { turbo_method: :patch } do %>
                              <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 14v3m-3-6V7a3 3 0 1 1 6 0v4m-8 0h10a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1v-7a1 1 0 0 1 1-1Z"/>
                              </svg>
                            <% end %>
                          <% else %>
                            <%= link_to activate_user_path(user), data: { turbo_method: :patch } do %>
                              <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14v3m4-6V7a3 3 0 1 1 6 0v4M5 11h10a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-7a1 1 0 0 1 1-1Z"/>
                              </svg>
                            <% end %>
                          <% end %>
                      <% end %>
                 <% end %>
            </div>
          </td>
        </tr>

        <%= form_with(url: user_path(user), method: :delete, class: "delete-form hidden", data: { user_id: user.id }) do |f| %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<div class="flex flex-col items-center mt-4">
  <!-- Texto de ayuda -->
  <span class="text-sm text-gray-700 dark:text-gray-400">
    Viendo 
    <span class="font-semibold text-gray-900 dark:text-white"><%= @users.offset_value + 1 %></span>
    a 
    <span class="font-semibold text-gray-900 dark:text-white"><%= [@users.offset_value + @users.limit_value, @users.total_count].min %></span> 
    de 
    <span class="font-semibold text-gray-900 dark:text-white"><%= @users.total_count %></span> Usuarios
  </span>

  <div class="inline-flex mt-2 xs:mt-0">
  <!-- Botón "Anterior" -->
  <% if @users.prev_page %>
    <%= link_to users_path(page: @users.prev_page), class: "flex items-center justify-center px-3 h-8 text-sm font-medium text-white bg-gray-800 rounded-s hover:bg-gray-900 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white" do %>
      <svg class="w-3.5 h-3.5 me-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5H1m0 0 4 4M1 5l4-4"/>
      </svg>
      Anterior
    <% end %>
  <% else %>
    <button class="flex items-center justify-center px-3 h-8 text-sm font-medium text-gray-400 bg-gray-200 rounded-s cursor-not-allowed dark:bg-gray-700 dark:text-gray-500" disabled>
      <svg class="w-3.5 h-3.5 me-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5H1m0 0 4 4M1 5l4-4"/>
      </svg>
      Anterior
    </button>
  <% end %>

  <!-- Botón "Siguiente" -->
  <% if @users.next_page %>
    <%= link_to users_path(page: @users.next_page), class: "flex items-center justify-center px-3 h-8 text-sm font-medium text-white bg-gray-800 border-0 border-s border-gray-700 rounded-e hover:bg-gray-900 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white" do %>
      Siguiente
      <svg class="w-3.5 h-3.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
      </svg>
    <% end %>
  <% else %>
    <button class="flex items-center justify-center px-3 h-8 text-sm font-medium text-gray-400 bg-gray-200 border-0 border-s border-gray-700 rounded-e cursor-not-allowed dark:bg-gray-700 dark:text-gray-500" disabled>
      Siguiente
      <svg class="w-3.5 h-3.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
      </svg>
    </button>
  <% end %>
</div>




<div class="flex justify-center mt-6 gap-4 ">
  <%= link_to new_user_registration_path  do%>
    <button type="button" class="flex items-center justify-center h-full gap-2 text-white bg-rosa-light hover:rosa-hover focus:outline-none focus:rosa-pale font-medium rounded-full text-sm px-2 py-2 text-center">
      Agregar Usuario
      <svg class="ml-2 w-4 h-4 " aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14m-7 7V5"/>
      </svg>
    </button>
  <% end %>

   <%= link_to root_path  do%>
    <button type="button" class="flex items-center justify-center h-full gap-2 text-white bg-rosa-light hover:rosa-hover focus:outline-none focus:rosa-pale font-medium rounded-full text-sm px-4 py-2 text-center">
      Volver al inicio
    </button>
  <% end %>
</div>

<div id="popup-modal" tabindex="-1" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 flex items-center justify-center">
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <button type="button" class="absolute top-3 end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="popup-modal">
                <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                </svg>
                <span class="sr-only">Close modal</span>
            </button>
            <div class="p-4 md:p-5 text-center">
                <svg class="mx-auto mb-4 text-gray-400 w-12 h-12 dark:text-gray-200" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                </svg>
                <h3 class="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400">¿Estás seguro que querés eliminar este usuario?</h3>
                <button data-modal-hide="popup-modal" id="confirm-delete" data-user-id="" type="button" class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center">
                    Si, estoy seguro
                </button>
                <button data-modal-hide="popup-modal" type="button" class="py-2.5 px-5 ms-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">
                  No, cancelar
                </button>
            </div>
        </div>
    </div>
</div>


<script>
    document.addEventListener('DOMContentLoaded', () => {
      const deleteLinks = document.querySelectorAll('.delete-link');
      const modal = document.getElementById('popup-modal');
      const confirmDeleteButton = document.getElementById('confirm-delete');

      deleteLinks.forEach(link => {
        link.addEventListener('click', (e) => {
          e.preventDefault();
          
          const userId = link.getAttribute('data-user-id');

          // Mostrar modal
          modal.classList.remove('hidden');
          modal.setAttribute('aria-hidden', 'false');

          // Asignar el ID del usuario al botón de confirmación
          confirmDeleteButton.setAttribute('data-user-id', userId);
        });
      });

      // Modificar el botón de confirmación para enviar el formulario
      confirmDeleteButton.addEventListener('click', () => {
        const userId = confirmDeleteButton.getAttribute('data-user-id');
        
        // Buscar el formulario asociado y enviarlo
        const form = document.querySelector(`.delete-form[data-user-id="${userId}"]`);
        if (form) {
          form.submit();
        } else {
            console.error("No se encontró el formulario para el usuario ID:", userId);
        }
      });
      
        const cancelButton = modal.querySelector('[data-modal-hide="popup-modal"]');
        cancelButton.addEventListener('click', () => {
          modal.classList.add('hidden');
          modal.setAttribute('aria-hidden', 'true');
        });
    });

</script>

app/views/users/new.html.erb
<div class="flex justify-center items-center ">

    <%= form_with model: @user, html: { style: "width:50%; border: solid 1px black; border-radius:30px; padding:20px;"} do |form| %>
        
        <h1 class="text-center font-bold text-lg text-rosa-light mb-2">Nuevo Usuario</h1>
        <div class="mb-2">
            <%= form.label :username, "Nombre de Usuario", class: "block text-sm font-medium text-gray-900 mb-2" %>
            <%= form.text_field :username, placeholder: "Ingrese el nombre de usuario", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-rosa-light focus:border-rosa-light block w-full p-2."%>
            <% @user.errors.full_messages_for(:username).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>

        <div class="mb-2">
            <%= form.label :email, "Correo electrónico", class: "mb-2 block text-sm font-medium text-gray-900" %>
            <%= form.email_field :email, placeholder: "Ingrese el correo electrónico", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-rosa-light focus:border-rosa-light block w-full p-2"%>
            <% @user.errors.full_messages_for(:email).each do |message| %>
            <div><%= message %></div>
            <% end %>
        </div>

        <div class="mb-2">
            <%= form.label :phone, "Número de Teléfono", class: "mb-2 block text-sm font-medium text-gray-900"%>
            <%= form.telephone_field :phone, placeholder: "Ingrese el número de teléfono", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-rosa-light focus:border-rosa-light block w-full p-2"%>
            <% @user.errors.full_messages_for(:phone).each do |message| %>
            <div><%= message %></div>
            <% end %>
        </div>

        <div class="mb-2">
            <%= form.label :original_password, "Contraseña", class: "mb-2 block text-sm font-medium text-gray-900"%>
            <%= form.password_field :original_password, placeholder: "Ingrese la contraseña", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-rosa-light focus:border-rosa-light block w-full p-2"%>
        </div>
        
        <div class="mb-2">
            <%= form.label :entry_date, "Fecha de entrada a la cadena", class: "mb-2 block text-sm font-medium text-gray-900"%>
            <%= form.date_field :entry_date, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-rosa-light focus:border-rosa-light block w-full p-2"%>
        </div>

        <div class="mb-2" >
            <%= form.label :role, "Selecciona un rol", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
            <%= form.select :role, User.roles.keys.map { |role| [role.humanize, role] }, { prompt: "Selecciona un rol" }, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
        </div>

        <div class="flex justify-center" >
            <%= form.submit "Crear Usuario", class: "bg-rosa-light text-white rounded-full
            hover:bg-opacity-90 transition duration-300 ease-in-out 
            focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-rosa-light w-1/2 mt-6" %>
        </div>
    <% end %>
</div>

app/views/users/show.html.erb
<h1>ESTOY EN EL SHOW</h1>